os:
  - linux
language: nix
before_install:
  - nix-env -iA nixpkgs.cachix
  - cachix use dapp
  - git clone --recursive https://github.com/dapphub/dapptools $HOME/.dapp/dapptools
  - nix-env -f $HOME/.dapp/dapptools -iA dapp solc
script:
  - dapp --use solc:0.5.12 test
