on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install nix 2.3.6
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://releases.nixos.org/nix/nix-2.3.6/install
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Use maker cachix
      uses: cachix/cachix-action@v10
      with:
        name: maker

    - name: Run tests
      run: nix-shell --pure --run 'DAPP_BUILD_OPTIMIZE=0 DAPP_BUILD_OPTIMIZE_RUNS=0 DAPP_TEST_ADDRESS=0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B dapp --use solc:0.6.12 test'
